
# Define the services/containers to be run
services:
    frontend: # name of the first service
        build: angular-container # specify the directory of the Dockerfile
        ports:
            - "4200:4200" # specify port forwarding
        container_name: angular-container
        restart: always

    backend: # name of the second service
        build: nodejs-container # specify the directory of the Dockerfile
        ports:
            - "3000:3000" # specify ports forwarding
        container_name: nodejs-container
        restart: always
        links:
            - database # link this service to the database service
        depends_on:
            - database
    database: # name of the third service
        build: database-container # specify the directory of the Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        hostname: 127.0.0.1
        container_name: database-container
        restart: always